
name: Construction d'un projet

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCES_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: sonnyhardy/imc:latest

  server-deploy:
    name: server-deploy
    runs-on: ubuntu-latest
    steps:
      - name: create folder on remote VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker pull sonnyhardy/imc:latest
            docker stop imc-1 || true
            docker rm imc-1 || true
            docker run -d --name imc-1 -p 80:80 sonnyhardy/imc:latest


  #build:
   # runs-on: ubuntu-latest
    #steps:
     # - name: Telechargement des sources
      #  uses: actions/checkout@v4
      #- name: Set up JDK 17
       # uses: actions/setup-java@v4
        #with:
         # java-version: '17'
          #distribution: 'temurin'
          #cache: maven

      #- name: Build with Maven
       # run: mvn -Dmaven.test.skip=true -B package --file pom.xml